// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCAoMIbNw_hQ9XwxI0HfTEBWsuTyTmoLW0',
    appId: '1:684307438586:web:e75ebf523f9fe0e8d4a243',
    messagingSenderId: '684307438586',
    projectId: 'tvchatapp-3ba43',
    authDomain: 'tvchatapp-3ba43.firebaseapp.com',
    storageBucket: 'tvchatapp-3ba43.appspot.com',
    measurementId: 'G-FCF2LFV6W6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBT9macr87aIVAdURxbsS3qecia2HRdS8Q',
    appId: '1:684307438586:android:75626548a14ed89dd4a243',
    messagingSenderId: '684307438586',
    projectId: 'tvchatapp-3ba43',
    storageBucket: 'tvchatapp-3ba43.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_9QwCc7WyrYbdbEaOhhMhwB7Ywm6-1a8',
    appId: '1:684307438586:ios:80f8e0a31328a962d4a243',
    messagingSenderId: '684307438586',
    projectId: 'tvchatapp-3ba43',
    storageBucket: 'tvchatapp-3ba43.appspot.com',
    iosClientId: '684307438586-e5rdo06ftshf6hfvgddsqioqkpnhmf49.apps.googleusercontent.com',
    iosBundleId: 'com.example.hw4',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC_9QwCc7WyrYbdbEaOhhMhwB7Ywm6-1a8',
    appId: '1:684307438586:ios:3d3bcf0d264b4ea1d4a243',
    messagingSenderId: '684307438586',
    projectId: 'tvchatapp-3ba43',
    storageBucket: 'tvchatapp-3ba43.appspot.com',
    iosClientId: '684307438586-k6hmseb5d5sg5minnnbvel7h2lfrkd06.apps.googleusercontent.com',
    iosBundleId: 'com.example.hw4.RunnerTests',
  );
}
